image: node:7.9.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    # Cleanup old files.
    - rm -rf public
    # Copy website files to root.
    - mkdir public
    - mv website/* public
    - mkdir -p public/.well-known/acme-challenge
    - mv website/.well-known/* public/.well-known
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
