name: personal-website-proxy-web
runtime: yaml
description: Deploys the proxy web infra

variables:
  domain: gchristov.com
  location: europe-west1
  repositoryId: personal-website

resources:

  ########################################
  # Stack references
  ########################################

  landing-page-web-reference:
    type: pulumi:pulumi:StackReference
    properties:
      name: gchristov/personal-website-landing-page-web/prod

  ########################################
  # proxy-web-service
  ########################################

  # Manages the binary.
  proxy-web-service-binary:
    type: docker:Image
    properties:
      build:
        args:
          LANDING_PAGE_WEB_SERVICE_HOST: ${landing-page-web-reference.outputs["landingPageWebServiceHost"]}
        platform: linux/amd64
        context: ../service/build/dist/js
      imageName: ${location}-docker.pkg.dev/${gcp:project}/${repositoryId}/proxy-web-service:latest
      registry:
        server: ${location}-docker.pkg.dev
        username: _json_key
        password:
          fn::secret:
            fn::readFile: ${gcp:credentials}
    options:
      protect: true
  # Manages the Cloud Run service.
  proxy-web-service:
    type: gcp:cloudrunv2:Service
    properties:
      ingress: INGRESS_TRAFFIC_ALL
      location: ${location}
      name: proxy-web-service
      template:
        containers:
          - image: ${proxy-web-service-binary.repoDigest}
            ports:
              - containerPort: 80
                name: http1
            resources:
              cpuIdle: true
              limits:
                cpu: 1000m
                memory: 512Mi
            startupProbe:
              failureThreshold: 1
              periodSeconds: 240
              tcpSocket:
                port: 80
              timeoutSeconds: 240
        maxInstanceRequestConcurrency: 80
        scaling:
          maxInstanceCount: 100
          minInstanceCount: 0
        timeout: 300s
      traffics:
        - percent: 100
          type: TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST
    options:
      protect: true
  # Manages the Cloud Run service policy.
  proxy-web-service-policy:
    type: gcp:cloudrunv2:ServiceIamPolicy
    properties:
      name: ${proxy-web-service.name}
      location: ${location}
      policyData: |
        {
          "bindings": [
            {
              "role": "roles/run.invoker",
              "members": [
                "allUsers"
              ]
            }
          ]
        }
    options:
      protect: true
  # Manages the Cloud Run service domain mapping.
  proxy-web-service-domain-mapping:
    type: gcp:cloudrun:DomainMapping
    properties:
      location: ${proxy-web-service.location}
      metadata:
        namespace: ${gcp:project}
      name: ${domain}
      spec:
        routeName: proxy-web-service
    options:
      protect: true