services:
  proxy-web-service:
    build: ../proxy-web/service/build/dist/js
    ports:
      - "8080:80" # host:container
    environment:
      - LANDING_PAGE_WEB_SERVICE_HOST=http://landing-page-web-service:80