name: common-deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'

env:
  GCP_SA_KEY_INFRA: ${{ secrets.GCP_SA_KEY_INFRA }}

jobs:
  common-deploy-build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}-common-deploy-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up secrets
        run: |
          echo "$GCP_SA_KEY_INFRA" >> ./common/infra/credentials-gcp-infra.json
      - name: Deploy infrastructure
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod
          work-dir: common/infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Build
          path: |
            common/infra