name: common-check

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**'

env:
  GCP_SA_KEY_INFRA: ${{ secrets.GCP_SA_KEY_INFRA }}

jobs:
  common-check-build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}-common-check-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up secrets
        run: |
          echo "$GCP_SA_KEY_INFRA" >> ./common/infra/credentials-gcp-infra.json
      - name: Preview infrastructure
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: prod
          work-dir: common/infra
          pulumi-version: "3.109.0"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Build
          path: |
            common/infra